# OOP's Continue...

In [5]:
class Arthimetics:
    
    def addition(self, a, b):
        return a+b
    def subtraction(self, a, b):
        return a-b
    def mul(self, a, b):
        return a*b

In [6]:
obj = Arthimetics()

In [3]:
obj.addition()

TypeError: addition() missing 2 required positional arguments: 'a' and 'b'

In [7]:
obj.addition(12,89)

101

In [8]:
obj.subtraction(89,23)

66

In [9]:
obj.mul(12,32)

384

## Constructor  (`__init__()` )

Constructor method is automatically exicuted while creating a object

In [10]:
dir(Arthimetics)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'addition',
 'mul',
 'subtraction']

In [13]:
class SampleConstructor():
    def __init__(self):
        print("it is constructor")
    def Test_method(self):
        return "normal method"

In [14]:
val = SampleConstructor()

it is constructor


In [15]:
val.Test_method()

'normal method'

In [55]:
class Arth():
    def __init__(self, val1, val2):
        self.val1= val1   # defining class variables 
        self.val2 = val2
    def add(self):
        return self.val1+ self.val2
    def mul(self):
        return self.val1 * self.val2

In [56]:
obj = Arth()

TypeError: __init__() missing 2 required positional arguments: 'val1' and 'val2'

In [57]:
obj = Arth(12,2)

In [58]:
obj.add()

14

In [59]:
obj.mul()

24

## `__str__`


In [17]:
print(val)

In [18]:
print(obj)

In [19]:
class ClassStr():
    def __str__(self):
        return "you are trying to print ClassStr class..!!"

In [20]:
cs = ClassStr()

In [22]:
print(cs)

you are trying to print ClassStr class..!!


## `__del__` 

Destructor, called when the instance is about to be destroyed

In [23]:
del cs

In [24]:
del obj

In [48]:
class classDel():
    def __del__(self):
        print("the object distroyed ..!!")

In [49]:
a = classDel()

In [50]:
del a

the object distroyed ..!!


In [51]:
c = classDel()

In [52]:
del c

the object distroyed ..!!


Main building blocks of object oriented Programming
- Inheritance
- Polymorphism
- Encapsulation
- Abstraction
## Inheritance

Inheritance is a way of creating new class using details of existing class without modifying it.

the newly formed class called as child class

In [60]:
obj1 = Arth(12,34)

In [61]:
class ChildArth(Arth):
    def disp(self):
        return "child class"

In [62]:
issubclass(ChildArth,Arth)

True

In [63]:
child = ChildArth()

TypeError: __init__() missing 2 required positional arguments: 'val1' and 'val2'

In [64]:
child = ChildArth(2,4)

In [65]:
child.disp()

'child class'

In [66]:
child.add()

6

In [67]:
child.mul()

8

In [68]:
class Parent():
    def m1(self):
        return "method 1"

In [69]:

class Child(Parent):
    def m2(self):
        return "method 2"

In [70]:
p = Parent()

In [71]:
p.m1()

'method 1'

In [72]:
p.m2()

AttributeError: 'Parent' object has no attribute 'm2'

In [73]:
c = Child()

In [74]:
c.m2()

'method 2'

In [75]:
c.m1()

'method 1'

### Calling Super class variables (attributes)

In [121]:
class Parent1():
    a = 10
    b = 23

In [122]:
class Child1(Parent1):
    x = 4
    y = 7
    def addition(self):
        print(self.x + self.y)
        print(self.a + self.b)

In [123]:
k = Child1()

In [125]:
k.x, k.y

(4, 7)

In [85]:
k.addition()

11
33


In [90]:
class Parent2():
    a  = 11
    b = 9
    
    
class Child2(Parent2):
    a = 4
    b = 7
    def addition(self):
        print(self.a + self.b)
        print(super().a + super().b)

In [91]:
c2 = Child2()

In [92]:
c2.addition()

11
20


1. Single Inheritance  
2. Multilevel Inheritance
3. Multiple Inheritance
4. Hierachical inheritance
5. Hybrid Inheritance

### Single Inheritance 
Single parent and single child

In [93]:
class Parent():
    pass
class Child(Parent):
    pass

### Multilevel Inheritance
Level by level

In [95]:
class GrandParent():
    pass
class Parent(GrandParent):
    pass
class Child(Parent):
    pass

### Multiple Inheritance
One chiled as multiple parents

In [96]:
class A:
    pass
class B:
    pass

class C(A,B):
    pass

In [97]:
class parent1():
    def m1(self):
        print('from p1 m1..')
class parent2():
    def m2(self):
        print('from p2 m2..')
        
        
class child(parent1,parent2):
    def m3(self):
        print('from m3 child')

In [98]:
c = child()

In [99]:
c.m3()

from m3 child


In [101]:
c.m2()

from p2 m2..


In [102]:
c.m1()

from p1 m1..


### Hierachical inheritance

one parent with multiplr child

In [103]:
class A():
    pass
class child1(A):
    pass
class child2(A):
    pass

## Polymorphism

one functionality with multiple behaviour

or 

the ability to appear in more then on e form

In [104]:
len([1,2,3,4])

4

In [105]:
len('string..')

8

In [106]:
s = 'abc'

In [107]:
s.upper()

'ABC'

In [108]:
'abc'.upper()

'ABC'

In [109]:
class parent():
    def name(self):
        return "abcd"

In [110]:
class child(parent):
    def name(self):
        return 'xyz'

In [112]:
c = child()

In [113]:
c.name()

'xyz'

## Encapsulation
The process of binding the data (binding the data means other person cannot access our data)

for that binding the data we need to use private modifiers (__)

In [114]:
class AA:
    __a = 10 # private attribute
    def disp(self):
        return self.__a

In [116]:
AA().disp()

10

In [117]:
obj = AA()

In [118]:
dir(obj)

['_AA__a',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'disp']

In [119]:
obj.disp()

10

In [120]:
obj.__a

AttributeError: 'AA' object has no attribute '__a'

In [130]:
class Myclass:
    def __m1(self): # private method
        print("this is private method ")
    def m2(self):
        print("this is normal method")
        self.__m1()

In [131]:
obj2 = Myclass()

In [132]:
obj2.__m1()

AttributeError: 'Myclass' object has no attribute '__m1'

In [133]:
obj2.m2()

this is normal method
this is private method 


### Abstraction 
the process of highlighting the service and hiding the implementation in child class

Abstraction class is just for showing declarations but not implimentations

In [134]:
from abc import ABC, abstractmethod

In [135]:
class A(ABC):
    @abstractmethod
    def m1(self):
        pass

In [136]:
class B(ABC):
    @abstractmethod
    def disp(self):
        pass
    
class C(B):
    def disp(self):
        print('hi')

In [137]:
a = C()

In [138]:
a.disp()

hi


In [139]:
b = B()

TypeError: Can't instantiate abstract class B with abstract methods disp

In [141]:
class Person(ABC):
    @abstractmethod
    def work(self):
        pass

In [142]:
class Student(Person):
    def work(self):
        print('studying')

class Faculty(Person):
    def work(self):
        print('teaching')

In [143]:
student = Student()

In [144]:
student.work()

studying


In [145]:
[1,2,3,4,5,6,7,6]

[1, 2, 3, 4, 5, 6, 7, 6]

In [146]:
list(range(1,100))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

# Numpy : Numerical python
    
    
N dimentional array

In [148]:
import numpy

In [150]:
a = numpy.array(list(range(100)))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [152]:
a.shape

(100,)

In [154]:
a1 = numpy.array([[1,2,3,4],[2,5,6,7]])

In [155]:
a1

array([[1, 2, 3, 4],
       [2, 5, 6, 7]])

In [156]:
a1.shape

(2, 4)

In [168]:
%%time
a*2

Wall time: 0 ns


array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [169]:
l = list(range(1,100))

In [170]:
%%time
for i in l:
    print(i*2)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
Wall time: 7.98 ms


In [171]:
a1

array([[1, 2, 3, 4],
       [2, 5, 6, 7]])

In [172]:
a3 = numpy.array([[1,2,3],[4,5,6],[4,5,6],[3,4,5]])

In [173]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [3, 4, 5]])