# NumPy

Numpy is a short form of Numerical python, is one of the most important foundational 
packeges for numerical Computing in python.
- NumPy operations performs complex computtaions on Entire arrays without the need of for loops
- NumPy arrays use much less memory then built in python sequences.


In [1]:
import numpy as np

In [3]:
a = np.array([1,2,4,5])

In [4]:
a

array([1, 2, 4, 5])

In [5]:
a.shape

(4,)

In [6]:
a1 = np.array([[3,5,6],[4,5,6]])

In [7]:
a1.shape

(2, 3)

In [8]:
a2 = np.array([[1,2],[3,4],[4,5],[1,3]])

In [9]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [11]:
a2.shape

(4, 2)

In [12]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [13]:
a3 = np.random.rand(2,3)

In [14]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [17]:
a3.shape

(2, 3)

### Arthmetics on arrays

In [18]:
a1

array([[3, 5, 6],
       [4, 5, 6]])

In [19]:
a1+a1

array([[ 6, 10, 12],
       [ 8, 10, 12]])

In [20]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [22]:
a2 *a2

array([[ 1,  4],
       [ 9, 16],
       [16, 25],
       [ 1,  9]])

In [23]:
a2.dtype

dtype('int32')

In [24]:
a3.dtype

dtype('float64')

In [25]:
b = np.array([['a','b','c'],[1,2,3]])

In [26]:
b

array([['a', 'b', 'c'],
       ['1', '2', '3']], dtype='<U1')

In [27]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [28]:
arr = np.arange(9)

In [35]:
arr1 = np.arange(10)

In [40]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
arr1.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.ones(2)

array([1., 1.])

In [52]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [53]:
np.ones((2,3,4,5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [54]:
a1

array([[3, 5, 6],
       [4, 5, 6]])

In [56]:
a1[1][1] = 22

In [57]:
a1

array([[ 3,  5,  6],
       [ 4, 22,  6]])

In [59]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

## Boolean Indexing

In [60]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [62]:
a2 < 4

array([[ True,  True],
       [ True, False],
       [False, False],
       [ True,  True]])

In [63]:
a2[a2 < 4]

array([1, 2, 3, 1, 3])

In [64]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [65]:
name = np.array(['raju', 'ravi', 'praveen', 'sagar'])

In [66]:
marks = np.array([78, 28, 37 , 89])

In [68]:
name[marks >= 35 ]

array(['raju', 'praveen', 'sagar'], dtype='<U7')

In [69]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [71]:
a2.argmin()

0

In [72]:
np.argmin(a2, axis = 1)

array([0, 0, 0, 0], dtype=int32)

In [74]:
np.argmin(a2, axis = 0)

array([0, 0], dtype=int32)

In [76]:
y = np.array([[23,45,2,45],[98,43,55,5]])

In [77]:
y

array([[23, 45,  2, 45],
       [98, 43, 55,  5]])

In [78]:
np.argmin(y)

2

In [79]:
np.argmin(y,  axis = 0)

array([0, 1, 0, 1], dtype=int32)

In [80]:
np.argmin(y, axis = 1)

array([2, 3], dtype=int32)

In [81]:
np.argmax(y)

4

In [83]:
y.sort()

In [84]:
y

array([[ 2, 23, 45, 45],
       [ 5, 43, 55, 98]])

In [85]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [86]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [87]:
np.save('test_array',a3)

In [88]:
np.load('test_array.npy')

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [91]:
y

array([[ 2, 23, 45, 45],
       [ 5, 43, 55, 98]])

In [92]:
np.save('y_array', y)

In [93]:
np.load('y_array.npy')

array([[ 2, 23, 45, 45],
       [ 5, 43, 55, 98]])

In [94]:
a1

array([[ 3,  5,  6],
       [ 4, 22,  6]])

In [95]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [96]:
np.savez('test_zip', x= a1, y=2)

In [101]:
h = np.load('test_zip.npz')

In [102]:
h['x']

array([[ 3,  5,  6],
       [ 4, 22,  6]])

In [103]:
h['y']

array(2)

In [104]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [106]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [107]:
np.savez('test_zip2',x=a3,y = a2)

In [108]:
u = np.load('test_zip2.npz')

In [109]:
u['x']

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [110]:
u['y']

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [111]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [112]:
np.transpose(a2)

array([[1, 3, 4, 1],
       [2, 4, 5, 3]])

In [114]:
a2.T

array([[1, 3, 4, 1],
       [2, 4, 5, 3]])

In [115]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

#### Linear algebra inverse matrixs


`np.linalg.inv`

In [126]:
a1

array([[ 3,  5,  6],
       [ 4, 22,  6]])

In [135]:
m = np.dot(a2,a2.T)

In [136]:
m

array([[ 5, 11, 14,  7],
       [11, 25, 32, 15],
       [14, 32, 41, 19],
       [ 7, 15, 19, 10]])

In [137]:
np.linalg.inv(m)

array([[-1.40737488e+15, -2.81474977e+14,  4.02107110e+14,
         6.43371375e+14],
       [ 2.81474977e+14,  8.44424930e+14, -6.43371375e+14,
        -2.41264266e+14],
       [-0.00000000e+00, -5.62949953e+14,  4.02107110e+14,
         8.04214219e+13],
       [ 5.62949953e+14,  0.00000000e+00, -8.04214219e+13,
        -2.41264266e+14]])

### Array Manipulations

In [139]:
y

array([[ 2, 23, 45, 45],
       [ 5, 43, 55, 98]])

In [140]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [141]:
y+a3

ValueError: operands could not be broadcast together with shapes (2,4) (2,3) 

In [143]:
a3

array([[0.39027137, 0.38499302, 0.12017192],
       [0.23884888, 0.31480335, 0.71145713]])

In [144]:
a1

array([[ 3,  5,  6],
       [ 4, 22,  6]])

In [150]:
np.concatenate([a1,a1])

array([[ 3,  5,  6],
       [ 4, 22,  6],
       [ 3,  5,  6],
       [ 4, 22,  6]])

In [153]:
np.concatenate((a1,a3))

array([[ 3.        ,  5.        ,  6.        ],
       [ 4.        , 22.        ,  6.        ],
       [ 0.39027137,  0.38499302,  0.12017192],
       [ 0.23884888,  0.31480335,  0.71145713]])

###  Vstack 

In [155]:
np.vstack([a1,a3])

array([[ 3.        ,  5.        ,  6.        ],
       [ 4.        , 22.        ,  6.        ],
       [ 0.39027137,  0.38499302,  0.12017192],
       [ 0.23884888,  0.31480335,  0.71145713]])

### Hstack

In [156]:
np.hstack([a1,a3])

array([[ 3.        ,  5.        ,  6.        ,  0.39027137,  0.38499302,
         0.12017192],
       [ 4.        , 22.        ,  6.        ,  0.23884888,  0.31480335,
         0.71145713]])

In [157]:
a1

array([[ 3,  5,  6],
       [ 4, 22,  6]])

### split

In [158]:
a1.resize(1,6)

In [159]:
a1

array([[ 3,  5,  6,  4, 22,  6]])

In [160]:
m,n, o = np.split(a1,[2,1])

In [161]:
m

array([[ 3,  5,  6,  4, 22,  6]])

In [162]:
n

array([], shape=(0, 6), dtype=int32)

In [163]:
o

array([], shape=(0, 6), dtype=int32)

In [164]:
p = np.arange(16)

In [166]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [167]:
np.split(p,[2,8])

[array([0, 1]),
 array([2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15])]

#### Stacking helpers: r and c

In [168]:
np.c_[1:16]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [169]:
np.r_[1:16]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Repeating element: tile and repeate

In [170]:
a = np.r_[1:16]

In [171]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [172]:
a.repeat(2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15])

In [173]:
a.repeat(3,axis= 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [174]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [175]:
a2.repeat(3,axis = 1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [4, 4, 4, 5, 5, 5],
       [1, 1, 1, 3, 3, 3]])

In [176]:
a2.repeat(3,axis = 0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [4, 5],
       [4, 5],
       [4, 5],
       [1, 3],
       [1, 3],
       [1, 3]])

In [178]:
np.tile(a2, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [4, 5, 4, 5],
       [1, 3, 1, 3]])

# Pandas

Pandas is also an open source Python Library proving high- performance data manipulation and analysis tool using its powerful data structures

Pandas:
- series 
- Data Frames

In [179]:
import pandas

#### Create a data Series with numpy array

In [181]:
arr = np.array([2,3,45,66])

In [183]:
pandas.Series(arr)

0     2
1     3
2    45
3    66
dtype: int32

In [184]:
pandas.DataFrame(arr)

0
0   2
1   3
2  45
3  66

In [185]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [186]:
pandas.DataFrame(a2)

0  1
0  1  2
1  3  4
2  4  5
3  1  3

In [187]:
import pandas as pd

#### Create a data Series with list

In [188]:
l = [1,2,3,4,5,6,7]

In [189]:
ds = pd.Series(l)

In [190]:
ds

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [191]:
str_list = list("abcdefghijklmnopqrstuvwxyz")

In [203]:
g = pd.Series(str_list)

#### Create a data Series with Dictionary

In [194]:
d = {'course': 'python', 'college':' rgukt', 'students':40, 'fee': np.nan }

In [195]:
d

{'course': 'python', 'college': ' rgukt', 'students': 40, 'fee': nan}

In [196]:
pd.Series(d)

course      python
college      rgukt
students        40
fee            NaN
dtype: object

In [207]:
df1 = pd.DataFrame(d,index=d.keys())

In [246]:
u = pd.read_csv('https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Data%20Analysis/Advertising.csv')

In [202]:
ds

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [204]:
g

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

#### Get values, indexs

In [205]:
g.values

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype=object)

In [206]:
g.index

RangeIndex(start=0, stop=26, step=1)

In [208]:
df1

course college  students  fee
course    python   rgukt        40  NaN
college   python   rgukt        40  NaN
students  python   rgukt        40  NaN
fee       python   rgukt        40  NaN

In [209]:
df1.values

array([['python', ' rgukt', 40, nan],
       ['python', ' rgukt', 40, nan],
       ['python', ' rgukt', 40, nan],
       ['python', ' rgukt', 40, nan]], dtype=object)

In [210]:
df1.columns

Index(['course', 'college', 'students', 'fee'], dtype='object')

In [211]:
df1['course']

course      python
college     python
students    python
fee         python
Name: course, dtype: object

In [213]:
g

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

#### Accesing  data using indexing

In [214]:
g[20]

'u'

In [219]:
d1 = {'name': ['satya', 'siva','ravi'],'age' : [23,24,21], 'branch': ['ece','cse', 'it']}

In [220]:
df2 = pd.DataFrame(d1)

In [221]:
df2

name  age branch
0  satya   23    ece
1   siva   24    cse
2   ravi   21     it

In [222]:
df2.values

array([['satya', 23, 'ece'],
       ['siva', 24, 'cse'],
       ['ravi', 21, 'it']], dtype=object)

In [223]:
df2.columns

Index(['name', 'age', 'branch'], dtype='object')

In [226]:
df2['name'][1]

'siva'

#### Using Numpay functiond: Masking and Mathematics

In [227]:
df2

name  age branch
0  satya   23    ece
1   siva   24    cse
2   ravi   21     it

In [229]:
df2[df2['age'] < 23]

name  age branch
2  ravi   21     it

In [230]:
#i += 2

In [231]:
df2['age'] < 23

0    False
1    False
2     True
Name: age, dtype: bool

In [232]:
df1

course college  students  fee
course    python   rgukt        40  NaN
college   python   rgukt        40  NaN
students  python   rgukt        40  NaN
fee       python   rgukt        40  NaN

In [237]:
df1.isna() # NaN values

course  college  students   fee
course     False    False     False  True
college    False    False     False  True
students   False    False     False  True
fee        False    False     False  True

In [238]:
df1.isnull()

course  college  students   fee
course     False    False     False  True
college    False    False     False  True
students   False    False     False  True
fee        False    False     False  True

In [239]:
df2.isnull()

name    age  branch
0  False  False   False
1  False  False   False
2  False  False   False

In [240]:
data = np.arange(16).reshape(4,4)

In [241]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [244]:
df3 = pd.DataFrame(data, columns = ['c1','c2','c3','c4'], index=['r1','r2','r3','r4'])

In [245]:
df3

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [248]:
df3.head(1)

c1  c2  c3  c4
r1   0   1   2   3

In [249]:
df3.head(3)

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11

In [251]:
df3.sample(1)

c1  c2  c3  c4
r1   0   1   2   3

In [252]:
u

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [253]:
u.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [254]:
u.sample()

Unnamed: 0     TV  radio  newspaper  sales
64          65  131.1   42.8       28.9   18.0

In [256]:
u.sample()

Unnamed: 0     TV  radio  newspaper  sales
53          54  182.6   46.2       58.7   21.2

In [257]:
u.sample(4)

Unnamed: 0     TV  radio  newspaper  sales
152         153  197.6   23.3       14.2   16.6
32           33   97.2    1.5       30.0    9.6
49           50   66.9   11.7       36.8    9.7
195         196   38.2    3.7       13.8    7.6

In [258]:
u

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [259]:
u.T

0     1     2      3      4     5     6      7    8      9    \
Unnamed: 0    1.0   2.0   3.0    4.0    5.0   6.0   7.0    8.0  9.0   10.0   
TV          230.1  44.5  17.2  151.5  180.8   8.7  57.5  120.2  8.6  199.8   
radio        37.8  39.3  45.9   41.3   10.8  48.9  32.8   19.6  2.1    2.6   
newspaper    69.2  45.1  69.3   58.5   58.4  75.0  23.5   11.6  1.0   21.2   
sales        22.1  10.4   9.3   18.5   12.9   7.2  11.8   13.2  4.8   10.6   

            ...    190    191    192    193    194    195    196    197  \
Unnamed: 0  ...  191.0  192.0  193.0  194.0  195.0  196.0  197.0  198.0   
TV          ...   39.5   75.5   17.2  166.8  149.7   38.2   94.2  177.0   
radio       ...   41.1   10.8    4.1   42.0   35.6    3.7    4.9    9.3   
newspaper   ...    5.8    6.0   31.6    3.6    6.0   13.8    8.1    6.4   
sales       ...   10.8    9.9    5.9   19.6   17.3    7.6    9.7   12.8   

              198    199  
Unnamed: 0  199.0  200.0  
TV          283.6  232.1  
radio        42.0    8.6  
newspaper    66.2    8.7  
sales        25.5   13.4  

[5 rows x 200 columns]

In [262]:
u.shape

(200, 5)

In [264]:
arr1.shape

(10,)

In [267]:
a= np.array([[1,2,3,5],[5,4,3,2],[4,34,5,6]])

In [268]:
a.shape

(3, 4)

In [270]:
s = np.random.rand(2,3,4)

In [281]:
s

array([[[0.92852003, 0.65802863, 0.20452374, 0.18709291],
        [0.78109039, 0.47611245, 0.15670173, 0.82952486],
        [0.65333088, 0.65383644, 0.33822466, 0.8722133 ]],

       [[0.97279587, 0.9448922 , 0.91980529, 0.91345998],
        [0.28687486, 0.6855634 , 0.31751131, 0.48608114],
        [0.29759014, 0.9930637 , 0.91247416, 0.29853418]]])

In [271]:
s.shape

(2, 3, 4)

In [273]:
a2

array([[1, 2],
       [3, 4],
       [4, 5],
       [1, 3]])

In [274]:
n = np.dot(a2, a2.T)

In [275]:
n

array([[ 5, 11, 14,  7],
       [11, 25, 32, 15],
       [14, 32, 41, 19],
       [ 7, 15, 19, 10]])

In [276]:
np.linalg.inv(n)

array([[-1.40737488e+15, -2.81474977e+14,  4.02107110e+14,
         6.43371375e+14],
       [ 2.81474977e+14,  8.44424930e+14, -6.43371375e+14,
        -2.41264266e+14],
       [-0.00000000e+00, -5.62949953e+14,  4.02107110e+14,
         8.04214219e+13],
       [ 5.62949953e+14,  0.00000000e+00, -8.04214219e+13,
        -2.41264266e+14]])

In [278]:
a7 = np.array([[1,2,3],[4,3,1],[8,7,5]])

In [279]:
a7

array([[1, 2, 3],
       [4, 3, 1],
       [8, 7, 5]])

In [280]:
np.linalg.inv(a7)

array([[-2.  , -2.75,  1.75],
       [ 3.  ,  4.75, -2.75],
       [-1.  , -2.25,  1.25]])